name: sdc_env
channels:
  - conda-forge
dependencies:
  - python==3.12.12
  - cftime
  - dask
  - dask-jobqueue
  - dask-labextension
  - datashader
  - flox
  - geopandas
  - gdal
  - hvplot
  - h5netcdf
  - jupyterlab
  - jupyter-book == 1.0.4
  - libgdal-arrow-parquet
  - matplotlib
  - nodejs
  - numbagg
  - odc-stac
  - planetary-computer
  - rioxarray
  - rio-cogeo
  - rio-stac
  - spyndex
  - xarray
  - xarray-spatial
  - xvec
